### ISSUE TITLE
Points cloud topic (stereo version)

### ISSUE THREAD

**Issue by lippiello** [srv/viso2#1]
Is ti possible to publish also a topic with the points cloud in the body fixed (current) frame and in the base frame (optionally)?

thank for the great work!!!

**Comment by stwirth** [comment]
I just added point cloud publishing to the stereo_odometer. The point cloud is published in the camera frame (as given in incoming camera_info msg). If you need the point cloud in another frame, please use [TransformListener::transformPointCloud()](http://ros.org/doc/electric/api/tf/html/c++/classtf_1_1TransformListener.html#afccbdbc27da4dceff41b85580a48d0f3)

**Comment by lippiello** [comment]
Dear Stephan,

thank you very much for your kindly and so rapid intervention.

Best regards
Vincenzo Lippiello

-----Messaggio originale-----
Da: Stephan [mailto:reply@reply.github.com] 
Inviato: lunedì 26 marzo 2012 11:45
A: lippiello
Oggetto: Re: [srv_vision] Points cloud topic (stereo version) (#1)

I just added point cloud publishing to the stereo_odometer. The point cloud is published in the camera frame (as given in incoming camera_info msg). If you need the point cloud in another frame, please use [TransformListener::transformPointCloud()](http://ros.org/doc/electric/api/tf/html/c++/classtf_1_1TransformListener.html#afccbdbc27da4dceff41b85580a48d0f3)

---

**Comment by lippiello** [comment]
> Stephan,
> do you think it is possible to add the option replace=true as a ros
> parameter to set at running time? Is it even possible to set parameters
> without changing those in the program? If yes in which way?
> Thanks
> 
> Giuseppe

**Comment by stwirth** [comment]
Hi Vincenzo, please note that I just renamed the stack and a containing package. To keep up with the change, just change the remote URL in your local clone to the new one (srv_vision.git => viso2.git) and run an update. The ROS wiki will take a while to get the documentation updated.
