### ISSUE TITLE
Variance vs. standard deviation

### ISSUE THREAD

**Issue by pavel-kirienko** [srv/viso2#12]
[Consider these lines.](https://github.com/srv/viso2/blob/groovy/viso2_ros/src/stereo_odometer.cpp#L22-L29)

Since variance has units that are the square of the units of variable, the comment at line 22 is confusing. It should be like `0.1m^2 linear variance 10deg^2. angular variance`, or every member of the matrices below should be squared.

I suppose that the second assumption is correct?

**Comment by stwirth** [comment]
These are arbitrary values as viso2 does not compute any covariances. I added the '^2' to the comment as you suggested. Thanks for reporting!
