### ISSUE TITLE
E-mail incorrect?

### ISSUE THREAD

**Issue by limhyon** [srv/viso2#15]
I've sent an e-mail to your account but the user invalid error was returned.
So I posted the mail in here.

Hi.
I've seen your libviso2 ROS package on ros.org.
I really would like to run that on my computer, before doing so, I
have following questions.
- Compilation instruction for this package? : Could you provide brief
  compilation instruction for
  this ros package?
- Kitti dataset : Have you worked with Kitti dataset with this ROS
  package? Do you know how to
  provide existing image sequences to this ros package?
  - launch file : Can you provide some example launch file for real
    stereo system?

-Hyon

**Comment by miquelmassot** [comment]
Hi,

thanks for reporting! Let's begin:
- For compilation: in groovy you just need to do a catkin_make as usual. In Fuerte, do a rosmake inside viso2_ros package.
- Launch file: there's a demo stereo launchfile in viso2_ros/launch
- Dataset: as long as you provide the required ROS topics (images and camera info) you can use any dataset. If you want to use those, you'll need to publish these images as ROS topics.

If you have any other question, please feel free to ask, but in the future maybe it's better to ask in ROS answers.

**Comment by limhyon** [comment]
Thanks.
I'm downloading sample bag file from your ftp.
But in the demo.launch, disparity_params.yaml has been missed for your bag file.

By the way, what is your correct e-mail address?

**Comment by limhyon** [comment]
I set my demo.launch file as.
<arg name="bagfile" default="/home/hyon/Desktop/viso2_ros/amphoras-pool_2012-09-25-13-24-06_3.bag"/>

Then my disparity_params.yaml as

prefilter_size: 9
prefilter_cap: 31
correlation_window_size: 17
min_disparity: 20
disparity_range: 96
uniqueness_ratio: 10
texture_threshold: 10
speckle_size: 200
speckle_range: 4

However, I got following error.

auto-starting new master
process[master]: started with pid [28283]
ROS_MASTER_URI=http://hyon-gt683.local:11311

setting /run_id to defea280-0303-11e3-802d-b803054adee5
process[rosout-1]: started with pid [28296]
started core service [/rosout]
process[rosbag-2]: started with pid [28310]
process[stereo/stereo_image_proc-3]: started with pid [28335]
process[stereo_odometer-4]: started with pid [28348]
[ INFO] [1376280092.110923562]: Subscribing to:
    \* /stereo/left/image_rect
    \* /stereo/right/image_rect
    \* /stereo/left/camera_info
    \* /stereo/right/camera_info
[ INFO] [1376280092.452956765, 1348572246.314444471]: Basic Odometer Settings:
  odom_frame_id      = /odom
  base_link_frame_id = /base_link
  publish_tf         = true
[ WARN] [1376280107.442136375, 1348572261.304987165]: [stereo_processor] Low number of synchronized left/right/left_info/right_info tuples received.
Left images received:       0 (topic '/stereo/left/image_rect')
Right images received:      0 (topic '/stereo/right/image_rect')
Left camera info received:  0 (topic '/stereo/left/camera_info')
Right camera info received: 0 (topic '/stereo/right/camera_info')
Synchronized tuples: 0
Possible issues:
    \* stereo_image_proc is not running.
      Does `rosnode info /stereo_odometer` show any connections?
    \* The cameras are not synchronized.
      Try restarting the node with parameter _approximate_sync:=True
    \* The network is too slow. One or more images are dropped from each tuple.
      Try restarting the node, increasing parameter 'queue_size' (currently 5)

**Comment by limhyon** [comment]
I've corrected above problem by
arg name="camera" default="/stereo_down" 

However, it generates invalid pointcloud. And odometry does not move.

**Comment by limhyon** [comment]
Could you post complete demo.launch file to reproduce the result on below?
http://www.ros.org/wiki/viso2_ros?distro=groovy

Including tf static_transform_publisher?

**Comment by miquelmassot** [comment]
Hi Hyon,

check this launchflile as well as these params:

On 12 August 2013 06:40, Hyon Lim notifications@github.com wrote:

> Could you post complete demo.launch file to reproduce the result on below?
> http://www.ros.org/wiki/viso2_ros?distro=groovy
> 
> Including tf static_transform_publisher?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/srv/viso2/issues/15#issuecomment-22473072
> .

## 

Miquel Massot

miquel.massot@gmail.com
http://www.facebook.com/massothttp://www.twitter.com/resisteixhttp://gplus.to/massot

**Comment by miquelmassot** [comment]
Sorry, I answered from e-mail directly and tried to attach the file there.

Leave the default params, and in rviz use /odom as fixed frame and base_link as target frame

```
<launch>
<param name="/use_sim_time" value="true" />
<arg name="image"    default="image_rect_color" />
<arg name="stereo"   default="camera_comp_wide" />
<node pkg="tf" type="static_transform_publisher" name="base_link" args="0 -0.06 -0.1 -1.5708 3.1415 0.1745 /base_link $(arg stereo) 100" />
<group ns="$(arg stereo)">
<node pkg="stereo_image_proc" type="stereo_image_proc" name="proc" />
</group>
<node pkg="viso2_ros" type="stereo_odometer" name="stereo_odometer" output="screen">
<remap from="stereo" to="$(arg stereo)" />
<remap from="image" to="$(arg image)" />
</node> 
</launch>
```

**Comment by limhyon** [comment]
Hi. Which bag file were you testing?
Check actual launch file I'm running.
https://gist.github.com/limhyon/6209132

It still does not give a result, even it is not run properly.

**Comment by miquelmassot** [comment]
I left you a comment in the gist, I don't know if you've ever seen it. Can you check it?
