### ISSUE TITLE
VisoInfo.h not built

### ISSUE THREAD

**Issue by mikejmills** [srv/viso2#20]
VisoInfo.h not found

Already applied the fix from https://github.com/sksavant/viso2/blob/752aca9ab891a94bb456eedbeada355751f2e801/viso2_ros/CMakeLists.txt

mono_odometer.cpp:10:32: fatal error: viso2_ros/VisoInfo.h: No such file or directory

**Comment by miquelmassot** [comment]
Hi MikeJMills!

could you please provide more insight, please? I've tested viso2 hydro_devel branch in hydro and everything is fine. Can you post here which ROS distribution, Linux and branch are you using?

**Comment by mikejmills** [comment]
Sorry,

ROS hydro
.
Ubuntu 12.04
.
branch hydro-devel.

**Comment by miquelmassot** [comment]
Hi Mike,

I've tested again hydro-devel branch in a clean workspace and it's compiling without any issues. Could you please make sure that you have the latest version (git pull) of hydro-devel? The fix of sksavant is already applied in that branch, so I don't understand why did you have to apply that fix manually.

Try:

```
cd /tmp
mkdir -p hydro_test/src
cd hydro_test/src
source /opt/ros/hydro/setup.bash
catkin_init_workspace
git clone http://github.com/srv/viso2.git -b hydro-devel
cd ..
catkin_make
```

**Comment by mikejmills** [comment]
Thanks for responding so quickly.
I tried that here is the output.

mike@rosvm:/tmp/hydro_test$ catkin_make

Base path: /tmp/hydro_test

Source space: /tmp/hydro_test/src

Build space: /tmp/hydro_test/build

Devel space: /tmp/hydro_test/devel

Install space: /tmp/hydro_test/install

####

#### Running command: _"make cmake_check_build_system"_ in

_"/tmp/hydro_test/build"_

####

####

#### Running command: _"make -j1 -l1"_ in _"/tmp/hydro_test/build"_

####

[  7%] Building CXX object
viso2/libviso2/CMakeFiles/viso2.dir/libviso2/src/filter.cpp.o

[ 14%] Building CXX object
viso2/libviso2/CMakeFiles/viso2.dir/libviso2/src/matcher.cpp.o

[ 21%] Building CXX object
viso2/libviso2/CMakeFiles/viso2.dir/libviso2/src/matrix.cpp.o

[ 28%] Building CXX object
viso2/libviso2/CMakeFiles/viso2.dir/libviso2/src/reconstruction.cpp.o

[ 35%] Building CXX object
viso2/libviso2/CMakeFiles/viso2.dir/libviso2/src/triangle.cpp.o

[ 42%] Building CXX object
viso2/libviso2/CMakeFiles/viso2.dir/libviso2/src/viso.cpp.o

[ 50%] Building CXX object
viso2/libviso2/CMakeFiles/viso2.dir/libviso2/src/viso_mono.cpp.o

[ 57%] Building CXX object
viso2/libviso2/CMakeFiles/viso2.dir/libviso2/src/viso_stereo.cpp.o

_Linking CXX shared library /tmp/hydro_test/devel/lib/libviso2.so_

[ 57%] Built target viso2

[ 57%] Built target pcl_msgs_generate_messages_py

[ 57%] Built target nav_msgs_generate_messages_py

[ 57%] Built target nav_msgs_generate_messages_lisp

[ 57%] Built target sensor_msgs_generate_messages_py

[ 57%] Built target roscpp_generate_messages_cpp

[ 57%] Built target roscpp_generate_messages_py

[ 57%] Built target roscpp_generate_messages_lisp

[ 57%] Built target actionlib_msgs_generate_messages_cpp

[ 57%] Built target geometry_msgs_generate_messages_py

[ 57%] Built target geometry_msgs_generate_messages_lisp

[ 57%] Built target geometry_msgs_generate_messages_cpp

[ 57%] Built target actionlib_msgs_generate_messages_lisp

[ 57%] Built target std_msgs_generate_messages_lisp

[ 57%] Built target std_msgs_generate_messages_py

[ 57%] Built target rosgraph_msgs_generate_messages_cpp

[ 57%] Built target nav_msgs_generate_messages_cpp

[ 57%] Built target rosgraph_msgs_generate_messages_lisp

[ 57%] Built target rosgraph_msgs_generate_messages_py

[ 57%] Built target sensor_msgs_generate_messages_cpp

[ 57%] Built target sensor_msgs_generate_messages_lisp

[ 57%] Built target std_msgs_generate_messages_cpp

[ 57%] Built target tf_generate_messages_lisp

[ 57%] Built target actionlib_msgs_generate_messages_py

[ 57%] Built target tf2_msgs_generate_messages_py

[ 57%] Built target actionlib_generate_messages_lisp

[ 57%] Built target tf_generate_messages_cpp

[ 57%] Built target pcl_msgs_generate_messages_cpp

[ 57%] Built target nodelet_generate_messages_lisp

[ 57%] Built target tf_generate_messages_py

[ 57%] Built target pcl_ros_gencfg

[ 57%] Built target dynamic_reconfigure_generate_messages_py

[ 57%] Built target actionlib_generate_messages_cpp

[ 57%] Built target actionlib_generate_messages_py

[ 57%] Built target dynamic_reconfigure_generate_messages_cpp

[ 57%] Built target topic_tools_generate_messages_lisp

[ 57%] Built target topic_tools_generate_messages_cpp

[ 57%] Built target std_srvs_generate_messages_lisp

[ 57%] Built target nodelet_generate_messages_cpp

[ 57%] Built target tf2_msgs_generate_messages_cpp

[ 57%] Built target tf2_msgs_generate_messages_lisp

[ 57%] Built target nodelet_generate_messages_py

[ 57%] Built target std_srvs_generate_messages_py

[ 57%] Built target topic_tools_generate_messages_py

[ 57%] Built target std_srvs_generate_messages_cpp

[ 57%] Built target bond_generate_messages_cpp

[ 57%] Built target dynamic_reconfigure_generate_messages_lisp

[ 57%] Built target pcl_msgs_generate_messages_lisp

[ 57%] Built target bond_generate_messages_lisp

[ 57%] Built target bond_generate_messages_py

[ 64%] Building CXX object
viso2/viso2_ros/CMakeFiles/mono_odometer.dir/src/mono_odometer.cpp.o

/tmp/hydro_test/src/viso2/viso2_ros/src/mono_odometer.cpp:10:32: fatal
error: viso2_ros/VisoInfo.h: No such file or directory

compilation terminated.

make[2]: ***
[viso2/viso2_ros/CMakeFiles/mono_odometer.dir/src/mono_odometer.cpp.o]
Error 1

make[1]: **\* [viso2/viso2_ros/CMakeFiles/mono_odometer.dir/all] Error 2

make: **\* [all] Error 2

Invoking _"make"_ failed

mike@rosvm:/tmp/hydro_test$

_Mike Mills_
_PhD. Student, Robotics_
_University of Alberta_
_Canada_

**Comment by miquelmassot** [comment]
I've found a missing dependency between message generation and binaries. Can you test it please?

**Comment by mikejmills** [comment]
Sorry for the late reply I've been travelling.

That fixed worked, thanks for your help.

Cheers,

_Mike Mills_
_PhD. Student, Robotics_
_University of Alberta_
_Canada_

**Comment by miquelmassot** [comment]
Thanks for reporting

**Comment by tonystark12** [comment]
I am using ROS Indigo and am facing the same issue now. I got the package from

https://github.com/ZhuangYanDLUT/dlut_vision

Any fix for this one?

**Comment by stwirth** [comment]
@tonystark12 we do not maintain dlut_vision. Either try this repository or report your issue there.
