### ISSUE TITLE
Synchronization Problem

### ISSUE THREAD

**Issue by aba92** [srv/viso2#22]
Hi,

I've been trying to run your code with command,

 rosrun viso2_ros stereo_odometer stereo:=vizzy image:=image_rect_color _approximimate_sync:=True

 but I'm getting the following warning:

[ WARN] [1426508496.056623314, 225.349000000]: [stereo_processor] Low number of synchronized left/right/left_info/right_info tuples received.
Left images received:       16 (topic '/vizzy/left/image_rect_color')
Right images received:      15 (topic '/vizzy/right/image_rect_color')
Left camera info received:  16 (topic '/vizzy/left/camera_info')
Right camera info received: 16 (topic '/vizzy/right/camera_info')
Synchronized tuples: 0
Possible issues:
    \* stereo_image_proc is not running.
      Does `rosnode info /stereo_odometer` show any connections?
    \* The cameras are not synchronized.
      Try restarting the node with parameter _approximate_sync:=True
    \* The network is too slow. One or more images are dropped from each tuple.
      Try restarting the node, increasing parameter 'queue_size' (currently 5)

I don't know how to synchronize the camera's topics, I tried several codes that I found in ROS answers but I wasn't successful. The link to code:

http://answers.ros.org/question/9705/synchronizer-and-image_transportsubscriber/

Can you help me friend. Thank so much.

**Comment by plnegre** [comment]
The code you posted is used to check for synchronazed images, not to make the images synchonize, and is the same that viso2 has inside. Please read: http://wiki.ros.org/message_filters

If viso2 does not receive synchronized images, is a problem of your camera driver. Make sure that your driver is setting the field "header.timestamp" properly for each image topic.
