### ISSUE TITLE
Stereo Visual Odometry gives bad y direction estimation 

### ISSUE THREAD

**Issue by xgdongCMU** [srv/viso2#23]
Stereo Visual Odometry gives bad y direction estimation. Anyone know how to solve this problem?

**Comment by plnegre** [comment]
The stereo visual odometer has been successfully tested with a bumblebee 2. Thus, your problem could be due to poor calibration. Please, follow the instructions: http://wiki.ros.org/camera_calibration/Tutorials/StereoCalibration
