### ISSUE TITLE
Problem running viso2_ros

### ISSUE THREAD

**Issue by aba92** [srv/viso2#24]
Hello,

When running stereo_odometer, it appears a second robot blinking and with different position and orientation in rviz. That robot also appears in robot camera image, appears a second LaserScan and CostMap. I am not understanding why, and if you could help me I would be very grateful.

**Comment by miquelmassot** [comment]
Hi aba92, 

to me, it sounds like there's something wrong with your tf tree. Are you sure there is _only one parent_ for each tf frame?

**Comment by aba92** [comment]
Yes, I confirmed with rqt_tf_tree. Each frame has only one parent. I'm leaving here a image with what is happening...

![screenshot from 2015-04-20 16 02 47](https://cloud.githubusercontent.com/assets/11033365/7233042/d7884214-e776-11e4-8f6d-970f3618a2e6.png)

Please note on the cost map, the robot and the second robot on the camera images.

**Comment by miquelmassot** [comment]
rqt_tf_tree will only show one parent even if there's more than one. 

Take also into account the time rviz takes to update the images and the model in the window compared to the tf. I have also experienced unsync issues with urdf models and tfs, they update at different rates and sometimes you may see the robot in the camera image frame.

However, on cost maps I don't have any experience. Could you show us your viso2 tf configuration together with everything else? Is there a \base_link frame, an \odom, a \map?

**Comment by aba92** [comment]
Yes I have those frames available but I just tried to run the code with _publish_tf:=false and now everything seems to be going fine.

I have another issue (sorry man!), the point cloud output of stereo_odometer is represented in rviz world in a strange direction (z direction) but in the camera images the point cloud can be seen going along the corridor. Can you tell me on what I can be wrong, please.

![screenshot from 2015-04-20 16 35 01](https://cloud.githubusercontent.com/assets/11033365/7233876/902da602-e77b-11e4-8489-6cbf9245419b.png)

**Comment by miquelmassot** [comment]
It looks like your camera position is wrong. Check that the _Z_ of your camera is pointing towards the corridor, _Y_ is pointing downwards and _X_ to the right.

I'm closing the issue because this is not a problem related to viso2.
