### ISSUE TITLE
Using viso2 for monocular odometery

### ISSUE THREAD

**Issue by staljbs** [srv/viso2#26]
Hello,

I am trying to run  monocular odometer for viso2 and I get the following error :

[ WARN] [1435082098.253781281]: mono_odometer needs rectified input images. The used image topic is 'image'. Are you sure the images are rectified?
[ INFO] [1435082098.264686737]: Basic Odometer Settings:
  odom_frame_id      = /odom
  base_link_frame_id = /base_link
  publish_tf         = true
[ WARN] [1435082098.271895900]: Parameter 'camera_height' is required but not set. Using default: 1.000000
[ WARN] [1435082098.272378074]: Paramter 'camera_pitch' is required but not set. Using default: 0.000000
[ INFO] [1435082098.491839579]: Initialized libviso2 mono odometry with the following parameters:
Calibration parameters:
  f  = 0
  cu = 0
  cv = 0
Matcher parameters:
  nms_n                  = 3
  nms_tau                = 50
  match_binsize          = 50
  match_radius           = 200
  match_disp_tolerance   = 2
  outlier_disp_tolerance = 5
  outlier_flow_tolerance = 5
  multi_stage            = 1
  half_resolution        = 1
  refinement             = 1
Bucketing parameters:
  max_features  = 2
  bucket_width  = 50
  bucket_height = 50
Mono odometry parameters:
  camera_height    = 1
  camera_pitch     = 0
  ransac_iters     = 2000
  inlier_threshold = 1e-05
  motion_threshold = 100

[ WARN] [1435082098.510712066]: The tf from '/base_link' to 'usb_cam' does not seem to be available, will assume it as identity!
ERROR: Cannot get submatrix [3..3] x [0..-1] of a (0x0) matrix.

Terminal 3: roslaunch usb_cam.launch
The usb_cam node is publishing the images on the /camera/image_raw topic. 

My camera calibration parameters are all 0. Is that the problem? 

Can somebody help me with this? 
Thanks

**Comment by stwirth** [comment]
Yes, your camera calibration is the problem. Calibrate your camera first as shown here: http://wiki.ros.org/camera_calibration/Tutorials/MonocularCalibration

**Comment by santhoshrsk** [comment]
Hi, I am having same issue. I have calibrated my camera properly, but still getting same error.

The tf from '/base_link' to 'camera' does not seem to be available, will assume it as identity!
