### ISSUE TITLE
Building under ROS fuerte

### ISSUE THREAD

**Issue by LizMurphy** [srv/viso2#3]
Hi, I've had viso2_ros building and running fine under electric.  Switched over to fuerte yesterday and I get the following error when I try to build:

  [ 50%] Building CXX object CMakeFiles/mono_odometer.dir/src/mono_odometer.o
  Linking CXX executable bin/mono_odometer
  /usr/bin/ld: CMakeFiles/mono_odometer.dir/src/mono_odometer.o: undefined reference to symbol 'cv::fastFree(void_)'
  /usr/bin/ld: note: 'cv::fastFree(void_)' is defined in DSO /opt/ros/fuerte/lib/libopencv_core.so so try adding it to the linker command line
  /opt/ros/fuerte/lib/libopencv_core.so: could not read symbols: Invalid operation
  collect2: ld returned 1 exit status
  make[2]: **\* [bin/mono_odometer] Error 1
  make[1]: **\* [CMakeFiles/mono_odometer.dir/all] Error 2

Is this something to do with the way fuerte now releases opencv in the /opt/ros/fuerte/lib directory, and should I be linking against this version instead of the external opencv that electric must have used?

Cheers,
Liz

**Comment by stwirth** [comment]
Hi Liz, thanks for the report.
OpenCV was referenced the old (diamondback) way through a dependency on the opencv2 ROS package in the manifest. I changed the CMakeLists.txt of viso2_ros to use the system's OpenCV installation and fixed some tf-related issues for fuerte. I am happy that the package works now on fuerte, please confirm!

**Comment by LizMurphy** [comment]
Yep, just had the chance to download and install again and it all works fine now.  Thanks!

**Comment by stwirth** [comment]
Hi Liz, please note that I just renamed the stack and a containing package. To keep up with the change, just change the remote URL in your local clone to the new one (srv_vision.git => viso2.git) and run an update.

**Comment by LizMurphy** [comment]
## Thanks Stephan!

Liz Murphy
Postdoctoral Research Fellow
Faculty of Built Environment and Engineering, School of Engineering Systems,
Queensland University of Technology
S Block Level 11 1107
Phone: +61 7 31389971
Email: liz.murphy@qut.edu.au
