### ISSUE TITLE
Changes on the package name

### ISSUE THREAD

**Issue by yanming-zou** [srv/viso2#30]
I am a little confused by the changes on package names. What is the purpose of these changes? Are there any big changes in near future?

I am sorry if this is not the right place for this kind of discussion.

Best regards
Yanming

**Comment by miquelmassot** [comment]
Hi Yanming,

which changes are you refering to?

**Comment by yanming-zou** [comment]
I mean the package name dlut_viso2. The link in the wiki page of viso2 in ROS also points to another repository. But you are still the maintainer of the package. This situation is confusing to  me. I guess the latest stable version is kept in this repository. And it would be better if there is another wiki page for dlut_viso2 in ROS. What do you think?

**Comment by stwirth** [comment]
@ZhuangYanDLUT released viso2_ros viso2 under a synonym. libviso2 is now two times in the rosdistro index, I'll file an issue on https://github.com/ZhuangYanDLUT/dlut_vision.

**Comment by yanming-zou** [comment]
Hi Stephan,

I want to try the viso2 package but find the ROS bagfiles link
ftp://opt.uib.es/bagfiles/viso2_ros/ is obsolete. Could you help me to get
some samples? Thanks a lot.

Best regards
Yanming

2015-07-18 6:01 GMT+08:00 Stephan notifications@github.com:

**Comment by miquelmassot** [comment]
We have corrected this issue in #31 . Now bagfiles are at http://srv.uib.es/public/viso2_ros/sample_bagfiles/
