### ISSUE TITLE
rviz can't subscribe the output message /stereo_odometer/point_cloud

### ISSUE THREAD

**Issue by yanming-zou** [srv/viso2#32]
In the source code, the PointCloud type is defined as pcl::PointCloudpcl::PointXYZRGB by
                 typedef pcl::PointCloudpcl::PointXYZRGB PointCloud; (line 68, stereo_odometer.cpp)
The compiler thinks it is sensor_msgs::PointCloud2. 
But there are some differences between these 2 types: sensor_msgs::PointCloud2 and pcl::PointCloudpcl::PointXYZRGB. 
So rviz can't receive the message when I add the "PointCloud2" display and subscribe "stereo_odometer/point_cloud" in rviz. And the return of point_cloud_pub_.getNumSubscribers() (line 194) in stereo_odometer.cpp is always 0.

I think the above is the reason why I can't show the point cloud in rviz. Am I right? Thanks a lot.

Best regards
Yanming

**Comment by stwirth** [comment]
[pcl_ros](http://wiki.ros.org/pcl_ros) does the necessary conversion. There is no message type `pcl::PointCloud<pcl::PointXYZRGB>`. What do `rostopic info /stereo_odometer/point_cloud` and `rostopic hz /stereo_odometer/point_cloud` say?

**Comment by plnegre** [comment]
@stwirth is right, ROS makes the convertion between PCL and Points2 (see http://wiki.ros.org/pcl_ros#Publishing_point_clouds). In fact, I'm running viso2_ros just now and I'm able to see /stereo_odometer/point_cloud through the rviz.

**Comment by stwirth** [comment]
Closing as not an issue of the library.

**Comment by yanming-zou** [comment]
Thank you all for the help.

2015-07-25 0:32 GMT+08:00 Stephan notifications@github.com:
