### ISSUE TITLE
Lot of Features located in edges.

### ISSUE THREAD

**Issue by aba92** [srv/viso2#34]
Hello,

I'm using your code, but also using the rejected outliers. So I found that there are some features located at edges. Once they are only matched points, I think that this shouldn't be possible. It is used SIFT, right? In this way, I think it should have a "elimination of keypoints located in edges".

I am thinking that changing some threshold, maybe the relative to matches one, would avoid this situation. I'm right?

I would appreciate your help. Thanks.

**Comment by stwirth** [comment]
@aba92,
no, the libviso2 library does not use SIFT. Please read the corresponding paper by the authors of the library:
Andreas Geiger and Julius Ziegler and Christoph Stiller: StereoScan: Dense 3d Reconstruction in Real-time.

Please note that we just provide the ROS wrapper for the algorithm, refer to the paper and the source code for in-depth information.
