### ISSUE TITLE
motion_estimate_valid

### ISSUE THREAD

**Issue by ghost** [srv/viso2#38]
Why the infomsg's field  _motion_estimate_valid_ isn't modified never during the program running? 
The same problem for _header.frame_id_.

> VisoInfo info_msg;
> info_msg.header.stamp = image_msg->header.stamp;
> info_msg.got_lost = !success;
> info_msg.change_reference_frame = false;
> info_msg.num_matches = visual_odometer_->getNumberOfMatches();
> info_msg.num_inliers = visual_odometer_->getNumberOfInliers();
> ros::WallDuration time_elapsed = ros::WallTime::now() - start_time;
> info_msg.runtime = time_elapsed.toSec();
> info_pub_.publish(info_msg);

thanks

**Comment by miquelmassot** [comment]
Hi @NikoGiovannini! No idea why. Do you need this information? Can you PR?
