### ISSUE TITLE
Feature Request - ROI suppression

### ISSUE THREAD

**Issue by benjaminabruzzo** [srv/viso2#48]
Greetings, 

I have an application where one robot is observing another robot directly, but I would like to mix in stereo odometry, but with suppression of features in the general region of the observed robot.  I an dig through your code and try hack it in myself, but I figured I would at least ask to see if this is in your pipeline for future releases.

Thank you,
Benjamin

**Comment by miquelmassot** [comment]
Hi @benjaminabruzzo, 

unfortunately, what you ask is not in our future plans or releases. Feel free to PR if you accomplish it and would like to contribute.

Best wishes,
M

**Comment by benjaminabruzzo** [comment]
Alright, thanks for the speedy response!
