### ISSUE TITLE
Stereo Odometer, free(): invalid pointer error ROS Kinetic

### ISSUE THREAD

**Issue by suneelbelkhale** [srv/viso2#49]
I'm running ROS Kinetic on an Odroid XU4, using two Flea3 GigE cameras as input. I followed the build procedure for viso2, and ran into the same -mmse3 error that others were finding (and the other issues listed on that issue thread due to the ARM processor as well). Now I have successfully built, but I am getting this error when I try to start up a stereo_odometer node.

Command: `rosrun viso2_ros stereo_odometer image:=image_rect`

This is the error output.
>[ INFO] [1455216526.819296799]: Subscribing to:
	* /stereo/left/image_rect
	* /stereo/right/image_rect
	* /stereo/left/camera_info
	* /stereo/right/camera_info
[ INFO] [1455216527.258145677]: Basic Odometer Settings:
  odom_frame_id      = odom
  base_link_frame_id = base_link
  publish_tf         = true
  invert_tf          = false
[ INFO] [1455216528.103928295]: Initialized libviso2 stereo odometry with the following parameters:
Calibration parameters:
  f  = 694.907
  cu = 333.242
  cv = 266.244
Matcher parameters:
  nms_n                  = 3
  nms_tau                = 50
  match_binsize          = 50
  match_radius           = 200
  match_disp_tolerance   = 2
  outlier_disp_tolerance = 5
  outlier_flow_tolerance = 5
  multi_stage            = 1
  half_resolution        = 1
  refinement             = 1
Bucketing parameters:
  max_features  = 2
  bucket_width  = 50
  bucket_height = 50
Stereo odometry parameters:
  base             = 0.101805
  ransac_iters     = 200
  inlier_threshold = 2
  reweighting      = 1
  queue_size = 5
  approximate_sync = 1
  ref_frame_change_method = 0
  ref_frame_motion_threshold = 5
  ref_frame_inlier_threshold = 150
*** Error in `/home/odroid/catkin_ws/devel/lib/viso2_ros/stereo_odometer': free(): invalid pointer: 0xafd8e020 ***
Aborted

One time I also got the following message at the end:
>*** Error in `/home/odroid/catkin_ws/devel/lib/viso2_ros/stereo_odometer': corrupted size vs. prev_size: 0x00a3bc70 ***
Aborted

Does anyone have any ideas for how to fix this? Thanks in advance.

**Comment by suijingfeng** [comment]
Hi. Your odroid XU4 has an ARM processor which indeed doesn't support Intels SSE intrinsics.
You can go into the header files of the libviso2 library and add a "compatibility" header like this one: https://github.com/otim/SSE-to-NEON

libviso2 use SSE set, it is mentioned in the stereoscan ...  author's paper.
