### ISSUE TITLE
Compile error - bullet port to tf

### ISSUE THREAD

**Issue by t-thanh** [srv/viso2#5]
Hi,

I got the compile error while compile viso2_ros:

In file included from /home/tienthanh/workspace/ros/groovy/mebios/nttputus/viso2/viso2_ros/src/mono_odometer.cpp:10:0:
/home/tienthanh/workspace/ros/groovy/mebios/nttputus/viso2/viso2_ros/src/odometer_base.h: In member function ‘void viso2_ros::OdometerBase::integrateAndPublish(const tf::Transform&, const ros::Time&)’:
/home/tienthanh/workspace/ros/groovy/mebios/nttputus/viso2/viso2_ros/src/odometer_base.h:153:9: error: ‘btScalar’ was not declared in this scope
/home/tienthanh/workspace/ros/groovy/mebios/nttputus/viso2/viso2_ros/src/odometer_base.h:153:18: error: expected ‘;’ before ‘angle’
/home/tienthanh/workspace/ros/groovy/mebios/nttputus/viso2/viso2_ros/src/odometer_base.h:155:44: error: ‘angle’ was not declared in this scope
/home/tienthanh/workspace/ros/groovy/mebios/nttputus/viso2/viso2_ros/src/odometer_base.h:155:44: note: suggested alternative:
/opt/ros/groovy/include/tf/LinearMath/Quaternion.h:406:1: note:   ‘tf::angle’
/home/tienthanh/workspace/ros/groovy/mebios/nttputus/viso2/viso2_ros/src/mono_odometer.cpp: In member function ‘void viso2_ros::MonoOdometer::imageCallback(const ImageConstPtr&, const CameraInfoConstPtr&)’:
/home/tienthanh/workspace/ros/groovy/mebios/nttputus/viso2/viso2_ros/src/mono_odometer.cpp:105:9: error: ‘btMatrix3x3’ was not declared in this scope
/home/tienthanh/workspace/ros/groovy/mebios/nttputus/viso2/viso2_ros/src/mono_odometer.cpp:105:21: error: expected ‘;’ before ‘rot_mat’
/home/tienthanh/workspace/ros/groovy/mebios/nttputus/viso2/viso2_ros/src/mono_odometer.cpp:109:9: error: ‘btVector3’ was not declared in this scope
/home/tienthanh/workspace/ros/groovy/mebios/nttputus/viso2/viso2_ros/src/mono_odometer.cpp:109:19: error: expected ‘;’ before ‘t’
/home/tienthanh/workspace/ros/groovy/mebios/nttputus/viso2/viso2_ros/src/mono_odometer.cpp:110:39: error: ‘rot_mat’ was not declared in this scope
/home/tienthanh/workspace/ros/groovy/mebios/nttputus/viso2/viso2_ros/src/mono_odometer.cpp:110:48: error: ‘t’ was not declared in this scope
make[2]: **\* [CMakeFiles/mono_odometer.dir/src/mono_odometer.cpp.o] Error 1
make[1]: **\* [CMakeFiles/mono_odometer.dir/all] Error 2
make: **\* [all] Error 2

I use ROS groovy, ubuntu 12.04. That could come from the porting of LinearMath from bullet to tf http://www.ros.org/wiki/bullet/ChangeList.

**Comment by miquelmassot** [comment]
Hi nttputus!

We have not yet tested viso2 with groovy. We are currently developing on Fuerte. As soon as we migrate to Groovy we will correct that.

**Comment by t-thanh** [comment]
I manage to build it on Groovy after following the instruction from https://github.com/youbot/youbot-ros-pkg/pull/4

**Comment by miquelmassot** [comment]
Thanks, we'll create a new branch for groovy with that.
