### ISSUE TITLE
viso2_ros cannot obtain the reconstruction

### ISSUE THREAD

**Issue by LjYURAS** [srv/viso2#52]
Hi, 
I am using viso2_ros with ROS indigo,  and the demo.launch seems work. 
However when I use rviz with PointCloud2(stereo_odometer/point_cloud), I get the Transform error: For frame [stereo_forward_optical]: Frame [stereo_forward_optical] does not exist. 

![screenshot from 2018-01-04 11_30_08](https://user-images.githubusercontent.com/13862040/34549339-ed4f55e6-f142-11e7-9bf4-3aa7c0aa6183.png)

Can you give me some advice to solve this problem? Thanks in advance.

**Comment by plnegre** [comment]
Can you run:
```
rosrun tf view_frames
```
and post the tf tree here?

**Comment by LjYURAS** [comment]
@plnegre  Thanks for your help. 

![image](https://user-images.githubusercontent.com/13862040/34556198-5fdf00b6-f170-11e7-9401-d870390b0c70.png)

Sorry, I do not know how can I change stereo_forward_optical to  stereo_forward

**Comment by plnegre** [comment]
What is the frame_id of your images? stereo_forward or stereo_forward_optical? Check it in the header of your image topic.

**Comment by LjYURAS** [comment]
@plnegre  I use test.bag downloaded from http://srv.uib.es/public/viso2_ros/sample_bagfiles and demo.launch in viso2_ros.  I do not modify these files. So I think the  frame_id is stereo_forward and I do not know why rviz need stereo_forward_optical.
![image](https://user-images.githubusercontent.com/13862040/34557352-efaa5e1c-f174-11e7-9d02-cf348a49f6a3.png)

**Comment by plnegre** [comment]
Ok, so in the demo.launch change this:

```
<param name="base_link_frame_id" value="$(arg camera)"/>
```

for this:

```
<param name="base_link_frame_id" value="stereo_forward_optical"/>
```

**Comment by LjYURAS** [comment]
@plnegre  It works. Thank you for your help!
