### ISSUE TITLE
compared with orb or surf ,What are the advantages and disadvantages of the feature used in the viso2 library 

### ISSUE THREAD

**Issue by Torchmm** [srv/viso2#79]
thanks to your very nice job!
compared with orb or surf ,What are the advantages and disadvantages of the feature used in the viso2 library ?

**Comment by bomiquel** [comment]
Hey @Torchmm! First of all, sorry for the late reply, there was no one assigned to the maintenance of this project.

We are not the creators of LIBVISO2, we have only developed a wrapper of this library for ROS. The creator is Andreas Geiger, I think these design questions should be addressed to him. I leave the official website of the library [here](https://www.cvlibs.net/software/libviso/)
