### ISSUE TITLE
Ideas about remappings

### ISSUE THREAD

**Issue by pavel-kirienko** [srv/viso2#9]
The way stereo node subscribes to image topics is good for command-line usage, but it is not very convenient if one needs to launch it from a launch file inside a namespace.

All of the improvements described below are applicable to the FOVIS wrapper too.
#### First issue

Consider a scenario: I have a namespace /stereo with a bunch of relevant nodes inside, like stereo_image_proc or camera drivers. It is preferred to keep all stereo-related nodes inside the same namespace, so I'd like to add stereo_odometer here too.

This is what I get in this case:

``` sh
$ ./stereo_odometer __ns:=/stereo

---
$ rosnode info /stereo/stereo_odometer 
# (not so interesting)
 * /stereo/stereo/right/stereo/image [unknown type]
 * /stereo/stereo/right/camera_info [unknown type]
 * /tf [tf/tfMessage]
 * /stereo/stereo/left/camera_info [unknown type]
 * /stereo/stereo/left/stereo/image [unknown type]
```

As you can see, the subscriptions were pushed down to the namespace `/stereo/stereo`, and this is not correct.
#### First suggestion

Use [rather standard](http://ros.org/wiki/stereo_image_proc) ROS API, subscribing to the topics `[left|right]/image`, `[left|right]/camera_info`.

If a user needs to use the node from command line, it is always possible to use a namespace, like that: `./stereo_odometer __ns:=/stereo`, or like that: `export ROS_NAMESPACE=/stereo && ./stereo_odometer`.
#### Second issue

In the scenario above it may be necessary to remap the image topics from `image` to something rather usable, like `image_rect`. In the most straightforward way it won't work:

``` sh
$ ./stereo_odometer __ns:=/stereo image:=image_rect

---
$ rosnode info /stereo/stereo_odometer 
# (not so interesting)
 * /stereo/stereo/right/stereo/image_rect [unknown type]
 * /stereo/stereo/right/camera_info [unknown type]
 * /tf [tf/tfMessage]
 * /stereo/stereo/left/camera_info [unknown type]
 * /stereo/stereo/left/stereo/image_rect [unknown type]
```

Remapping from `image` will be appended with current namespace, so we get `stereo/image_rect` instead of just `image_rect`.
#### Second suggestion

Use simple subscriptions to `[left|right]/image_rect`, `[left|right]/camera_info`. This is not very convenient for command-line usage, but it works with namespaces. Besides, VISO2 needs only `image_rect` anyway, this name is sort of standartized.

**Comment by pavel-kirienko** [comment]
I can provide a patch if you accept these suggestions.

**Comment by plnegre** [comment]
Hi pavel-kirienko, 

here, I would also suggest you to do a fork of our repository, make the changes and apply for a pull request. However, if you can't do these changes we will take into account in the following revisions.

**Comment by miquelmassot** [comment]
Hi pavel-kirienko,

this odometer is not intended to be launched inside a camera namespace. In a camera namespace you'll probably find drivers and an image_proc node, but not an odometer. The odometer subscribes to that camera images but its results (pose, odom) are not related to camera or image information. In my opinion, the odometer node must lie outside the camera namespace.
Furthermore, the remappings we did are best at launchfile usage. As an example:

``` xml
<node pkg="viso2_ros" type="stereo_odometer" name="viso2">
    <!-- image you want to feed to the odometer -->
    <remap from="image" to="image_rect" />    
    <!-- camera namespace -->
    <remap from="stereo" to="stereo_down" />  
</node>
```

**Comment by pavel-kirienko** [comment]
Hi Miquel,

I got the point about a camera namespace, but what will happen if one needs to push the odometer into a different namespace?

This won't work:

``` xml
<node pkg="viso2_ros" type="stereo_odometer" name="viso2" ns="/odometer_namespace">
    <!-- image you want to feed to the odometer -->
    <remap from="image" to="image_rect" />    
    <!-- camera namespace -->
    <remap from="stereo" to="stereo_down" />  
</node>
```

The current approach doesn't seem compatible with [pushing down](http://www.ros.org/wiki/Nodes#Remapping_Arguments.A.22Pushing_Down.22).

**Comment by pavel-kirienko** [comment]
This problem bothers me because I have the separated namespace `/cv` for vision-related tasks.

**Comment by miquelmassot** [comment]
If I launch that, then in a rostopic list I see

```
/odometer_namespace/stereo_down/left/camera_info
/odometer_namespace/stereo_down/left/odometer_namespace/image_rect
/odometer_namespace/stereo_down/right/camera_info
/odometer_namespace/stereo_down/right/odometer_namespace/image_rect
/odometer_namespace/viso2/info
/odometer_namespace/viso2/odometry
/odometer_namespace/viso2/point_cloud
/odometer_namespace/viso2/pose
```

you were right! I didn't see that namespace name in between the camera and the image. Sorry for that. I'll try to fix it whenever I can. I know the error comes from [here](https://github.com/srv/viso2/blob/master/viso2_ros/src/stereo_processor.h#L109-L110). Thanks for reporting!

**Comment by pavel-kirienko** [comment]
I'm glad we understand each other.

Let me provide a pull request for that, as Pep Lluís Negre suggested. It will be done tomorrow I believe.

**Comment by stwirth** [comment]
@pavel-kirienko Thanks for your suggestions!
The stereo subscription follows the style of [image_view stereo_view](http://www.ros.org/wiki/image_view#image_view.2BAC8-diamondback.stereo_view). To launch stereo nodes within a namespace you have to remap to a fully qualified image topic as well (yes, this is a little awkward):

```
$ rosrun viso2_ros stereo_odometer __ns:=cv stereo:=/stereo_forward image:=/image_rect
[ INFO] [1364312022.493148473]: Subscribing to:
* /stereo_forward/left/image_rect
* /stereo_forward/right/image_rect
* /stereo_forward/left/camera_info
* /stereo_forward/right/camera_info
```

Forcing the odometer to run inside the stereo camera namespace does not seem a good idea to me.
I'll close this issue, feel free to re-open if you find a better solution.

**Comment by pavel-kirienko** [comment]
> To launch stereo nodes within a namespace you have to remap to a fully qualified image topic as well (yes, this is a little awkward)

Awesome.
Seems that `nh.resolveName("image")` ([here](https://github.com/srv/viso2/blob/master/viso2_ros/src/stereo_processor.h#L109-L110)) remaps to the root namespace `/image_rect`, which is then prefixed by `/stereo_forward/side/`. That is not obvious.

Anyway, thanks for pointing that out!
